#pragma once

#include <cstdint>

enum class ObjectType : uint16_t
{
    nullObject = 0,
    table = 1,
    shelf = 2,
    books = 3,
    cabinet = 4,
    exitRect = 5,
    obstacleRect = 6,
    floorVent = 8,
    ceilingVent = 9,
    ceilingDuct = 10,
    candle = 11,
    leftFan = 12,
    rightFan = 13,
    clock = 16,
    paper = 17,
    grease = 18,
    bonusRect = 19,
    battery = 20,
    rubberBand = 21,
    lightSwitch = 24,
    outlet = 25,
    thermostat = 26,
    shredder = 27,
    powerSwitch = 28,
    guitar = 29,
    drip = 32,
    toaster = 33,
    ball = 34,
    fishBowl = 35,
    teaKettle = 36,
    window = 37,
    painting = 40,
    mirror = 41,
    basket = 42,
    macintosh = 43,
    upStairs = 44,
    downStairs = 45,
};
